-- MySQL Script generated by MySQL Workbench
-- Thu Aug 31 19:31:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema php_join
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema php_join
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `php_join` DEFAULT CHARACTER SET utf8 ;
USE `php_join` ;

-- -----------------------------------------------------
-- Table `php_join`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_join`.`especie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_join`.`animales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_join`.`animales` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdEspecie` INT NOT NULL,
  `Animales` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_animales_especie_idx` (`IdEspecie` ASC),
  CONSTRAINT `fk_animales_especie`
    FOREIGN KEY (`IdEspecie`)
    REFERENCES `php_join`.`especie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
